# Specify prior (same as initial proposal distribution)
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [-3,-3,-3,-3,-3]
    high: [3,3,3,3,3]

# Specify the inference model
model:
  engine: 'MCABC'  # ABC inference
  num_workers: 8  # Number of parallel workers
    
# Specify the neural training hyperparameters
train_args:
  num_simulations: 1000 
  quantile: 0.1 
  kde: True

device: 'cpu'  # Run on CPU
out_dir: './slcp/mcabc_obs1_N1000'  # Where to save the posterior
