# Specify prior
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [-3,-3,-3,-3,-3]
    high: [3,3,3,3,3]

# Specify the inference model
model:
  backend: 'sbi'
  engine: 'NRE'
  nets:
    - model: 'resnet'
      hidden_features: 50
      num_blocks: 2

# Specify the neural training hyperparameters
train_args:
  training_batch_size: 64
  learning_rate: 0.00001
  num_round: 10

device: 'cpu'  # Run on CPU
out_dir: './slcp/nre_obs1_N1000'  # Where to save the posterior
