name: ili_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pathlib
  - pyaml
  - pytorch
  - seaborn
  - pip:
    - pylians
    - sbi
