

posterior_file: 'toy_SNPE_posterior.pkl'
out_dir: './toy'
labels: ['t1', 't2', 't3']

ensemble_mode: True

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      seed: 123
      save_samples: True
      num_samples: 10000
      sample_method: 'direct'

  # coverages:
  #   module: 'ili.validation.metrics'
  #   class: 'PosteriorCoverage'
  #   args:
  #     num_samples: 100
  #     sample_method: 'direct'
  #     plot_list: ["coverage", "histogram", "predictions", "tarp"]


  # samples:
  #   module: 'ili.validation.metrics'
  #   class: 'PosteriorSamples'
  #   args:
  #     num_samples: 100
  #     sample_method: 'direct'
