in_dir: './toy'  # where to find initial data

xobs_file: 'x_obs.npy'  # the observed data around which to center simulations
thetafid_file: 'theta_obs.npy'  # only if true parameters are known

# x_file: 'x.npy'  # file name of the initial data
# theta_file: 'theta.npy'  # file name of the initial parameters
save_simulated: False
num_simulations: 2000  # number of simulations to generate per round
