
prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [0,0,0]
    scale: [1,1,1]

model:
  backend: 'sbi'
  engine: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'nsf'
      hidden_features: 32 
      num_transforms: 4
    # - model: 'maf'
    #   hidden_features: 64 
    #   num_transforms: 6
    # - model: 'mdn'
    #   hidden_features: 64 
    #   num_components: 5
    
train_args:
  training_batch_size: 64
  learning_rate: 0.0001
  num_round: 10  # number of rounds of simulations

device: 'cpu'
out_dir: './toy'
