
prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0.1, 0.5, 0.6]
    high: [0.5, 0.9, 1.0]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_data: 100
    n_hidden: [100,100,100]
    act_fn: "SiLU"

model:
  module: 'sbi.inference'
  class: 'SNPE_C'
  nets:
    - model: 'maf'
      hidden_features: 100 
      num_transforms: 2

train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: 'toy'
