
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0.1, 0.5, 0.6]
    high: [0.5, 0.9, 1.0]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_hidden: [100,100,100]
    act_fn: "SiLU"

model:
  backend: 'sbi'
  engine: 'NPE'  # Neural Posterior Estimation
  nets:
    - model: 'maf'
      hidden_features: 100 
      num_transforms: 2

train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
out_dir: 'toy'
