
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

model:
  module: 'sbi.inference'
  class: 'SNPE'
  name: 'toy_SNPE'
  nets:
    - model: 'maf'
      hidden_features: 50 
      num_transforms: 5
      signature: "maf"
    - model: 'mdn'
      hidden_features: 50 
      num_components: 6
    
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: './toy'
