# Specify prior
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [0,0,0]
    high: [1,1,1]

# Specify the inference model
model:
  backend: 'sbi'
  engine: 'NPE'  # Neural Posterior Estimation
  name: 'toy_NPE'
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50
      num_transforms: 5 
      signature: "maf"
      repeats: 3
    - model: 'mdn'  # Mixture Density Network
      hidden_features: 50 
      num_components: 6

# Specify the neural training hyperparameters
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'  # Run on CPU
out_dir: './toy'  # Where to save the posterior
