<<<<<<<< HEAD:examples/configs/val/quijote_sbi.yaml
backend: 'sbi'

========
>>>>>>>> main:examples/configs/val/quijote.yaml
posterior_path: 'toy/posterior.pkl'
output_path: 'toy'

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 1000
      labels: [ 'Omega_m', 'h', 'sigma_8' ]

  rank_stats:
    module: 'ili.validation.metrics'
    class: 'PlotRankStatistics'
    args:
      num_samples: 200
      labels: [ 'Omega_m', 'h', 'sigma_8' ]
