backend: 'pydelfi'

meta_path: './toy/tempmeta.pkl'
output_path: './toy'

metrics:
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'
    args:
      num_samples: 100
      labels: ['t1', 't2', 't3']

  rank_stats:
    module: 'ili.validation.metrics'
    class: 'PlotRankStatistics'
    args:
      num_samples: 10
      labels: ['t1', 't2', 't3']
