loader:
  module: 'ili.inference.loaders'
  class: 'SummarizerDatasetLoader'
  args:
    stage: 'train'
    data_dir: 'ltu-ili-data/quijote'
    summary_root_file: 'tpcf/z_0.50/quijote'
    param_file: 'latin_hypercube_params.txt'
    train_test_split_file: 'quijote_train_test_val.json'
    param_names: ['Omega_m', 'h', 'sigma_8']


prior:
  module: 'sbi.utils'
  class: 'BoxUniform'
  args:
    low: [0.1, 0.5, 0.6]
    high: [0.5, 0.9, 1.0]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_summary: 100
    n_hidden: [100,100,100]
    act_fn: "SiLU"

model:
  module: 'sbi.inference'
  class: 'SNPE_C'
  posterior_nn:
    model: 'mdn'
    hidden_features: 50
    num_components: 1

train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'
output_path: 'toy'
