name: run-notebooks

on:
  push:
    branches: [ "main", "uv" ]
  pull_request:
    branches: [ "main" ]



permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.6"
          python-version: "3.12"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Notebooks
        run: uv run jupyter nbconvert --config notebooks/mycfg.py


